# Generated by Django 5.0.3 on 2024-03-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioInterior', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('nomeCidade', models.CharField(max_length=50)),
                ('codCidade', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('nomeHospital', models.CharField(max_length=100)),
                ('codHospital', models.AutoField(primary_key=True, serialize=False)),
                ('sn_interior', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nomeUsuario', models.CharField(max_length=100)),
                ('cpfUsuario', models.CharField(max_length=14, unique=True)),
                ('emailUsuario', models.CharField(max_length=100)),
                ('senhaUsuario', models.CharField(max_length=10)),
                ('codUsuario', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
