# Configurações do Jekyll
title: Meu Site
description: Um site construído com Jekyll
theme: minima

# Configurações de URL
baseurl: "/formulario-carretinha" # Substitua este valor pelo caminho onde seu site será hospedado
url: "https://wesley-silva-hub.github.io" # Substitua este valor pela URL do seu projeto no GitHub Pages

# Outras configurações
markdown: kramdown
